# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jay's Site 
email: jay.w.reddy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A site to document any work that I would like to make public, and to show off
  cool static site generation using Pandoc/Jekyll. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  jaywreddy
# Plugins
gems:
  - jekyll-pandoc
pandoc:
  extensions:
    -mathjax

# Build settings
markdown: pandoc 
