# Site settings
title: My Stuff
name: Jay Reddy # your name
email: jay.w.reddy@gmail.com # your email address
description: >
    A Simple Jekyll Blog Theme. # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jaywreddy.github.io" # the base hostname & protocol for your site
github_username: jaywreddy # your Github username

google-analytics:  # add it if you have one

skillstree: false # turn on or off the skills tree in about page

# imports 
gems:
  - jekyll-pandoc
# Build settings
permalink: none
markdown: pandoc
pandoc:
  extensions:
    - smart
    - mathjax
